### PR TITLE
Update skilltreeinfo.json

### PR DESCRIPTION
**Pull request by Eden333**
- switched Reckless Princess & Wolf's Showtime

### CODE REVIEW

**Comment by Leayal** [comment]
Thank you for the fix.
You can delete the other old pull request, though.

**Comment by Eden333** [comment]
ok uhm, how do I do that? ^^

**Comment by Eden333** [comment]
ok it seems, that I can't even do that from what I've found.

"There is no way you can delete a pull request yourself -- you and the repo owner (and all users with push access to it) can close it, but it will remain in the log. This is part of the philosophy of not denying/hiding what happened during development.

However, if there are critical reasons for deleting it (this is mainly violation of Github Terms of Service), Github support staff will delete it for you."

**Comment by Eden333** [comment]
oh, should I click on "Delete branch"?
and I think you have to do the thing with your compiler again so It shows publicly.

**Pull request merged**
